#!/usr/bin/env python3
"""Build a self-contained @font-face CSS file with base64-embedded TTFs.

Run once at build time (and whenever the curated weight list changes):

    python3 shared/brand/_build_fonts_inline.py

Produces ``shared/brand/fonts_inline.css`` which the deliverable renderer
inlines so every HTML artifact opens correctly from ``file://`` or any
static host with the real SaaScend type — no external font requests.

Only a curated subset of weights actually used in deliverables is embedded,
to keep page weight as low as a self-contained doc allows.
"""
import base64
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
FONTS = HERE / "fonts"
OUT = HERE / "fonts_inline.css"

# (file, css family, weight, style)
CURATED = [
    ("Montserrat-SemiBold.ttf",  "Montserrat", 600, "normal"),
    ("Montserrat-Bold.ttf",      "Montserrat", 700, "normal"),
    ("Montserrat-ExtraBold.ttf", "Montserrat", 800, "normal"),
    ("OpenSans-Regular.ttf",     "Open Sans",  400, "normal"),
    ("OpenSans-Italic.ttf",      "Open Sans",  400, "italic"),
    ("OpenSans-SemiBold.ttf",    "Open Sans",  600, "normal"),
    ("OpenSans-Bold.ttf",        "Open Sans",  700, "normal"),
]


def main() -> None:
    blocks = [
        "/* SaaScend webfonts — base64-embedded subset for self-contained deliverables.",
        " * GENERATED by _build_fonts_inline.py. Do not edit by hand. */",
        "",
    ]
    for fname, family, weight, style in CURATED:
        path = FONTS / fname
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        blocks.append(
            "@font-face{"
            f"font-family:'{family}';font-weight:{weight};font-style:{style};"
            "font-display:swap;"
            f"src:url(data:font/ttf;base64,{b64}) format('truetype');"
            "}"
        )
    OUT.write_text("\n".join(blocks) + "\n", encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"Wrote {OUT.relative_to(HERE.parent.parent)} ({kb:.0f} KB, {len(CURATED)} faces)")


if __name__ == "__main__":
    main()
